### ISSUE TITLE
Runtime error: failed to select an activity

### ISSUE THREAD

**Issue by MelchiorUU** [lvanhee/COVID-sim#41] opened 2020-03-29 22:15 UTC
Running 1 week w/o infections.

Then change settings to infections.

Run for 200 ticks, get the following error:

log:
failed to select an activity
error while person 241 running ERROR
  called by procedure PERFORM-ACTIVITY (D:\phd\ASSOCC\COVID-sim\activity_model.nls)
  called by procedure PERFORM-PEOPLE-ACTIVITIES (D:\phd\ASSOCC\COVID-sim\activity_model.nls)
  called by procedure GO
  called by Command Center

org.nlogo.nvm.RuntimePrimitiveException: failed to select an activity
 at org.nlogo.prim.etc._error.perform(_error.scala:12)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.ExclusiveJob.run(ExclusiveJob.scala:39)
 at org.nlogo.nvm.Context.runExclusiveJob(Context.java:177)
 at org.nlogo.prim._asm_procedureperformpeopleactivitiesdphdassocccovidsimactivity_modelnls_ask_13.perform(:1)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: covid-sim

12:13:20.397 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
12:13:20.286 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
12:13:20.250 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
12:13:20.184 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:13:20.184 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
12:13:20.175 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
12:13:20.175 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
12:13:20.175 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
12:13:20.175 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
12:13:20.175 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

**Comment by rmellema** [comment] 2020-03-30 14:52
I have looked into this a bit, but cannot seem to reproduce it or figure out how it happened.
Do you remember more about the exact settings or things you did to get this to show up?

**Comment by rmellema** [comment] 2020-04-21 12:03
Since this has not popped up in a while and it is worth keeping the issue tracker clean, I'm closing this issue

**Closed as completed by rmellema** 2020-04-21 12:03 UTC
