### ISSUE TITLE
Error when running validation behavior space

### ISSUE THREAD

**Issue by maartenjensen** [lvanhee/COVID-sim#141] opened 2020-05-14 12:23 UTC
When running the following: show behaviourspace-global-fitness-value

It generated the first error when running the behaviourspace scenario 1 check was enabled, then I disabled that one and it did run scenario 3, but at the end of the last run created error 2. I think to me these errors are too far in the code. So hope someone can fix this.

ERROR 1
GATHERING-POINTS breed does not own variable AGE
error while gathering-point 25 running AGE
  called by procedure IS-WORKER? (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\social_networks.nls)
  called by procedure IS-WORKING-DAY-FOR-ME? (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\people_decision.nls)
  called by procedure PERFORM-PAYMENT-OF-FIXED-COSTS (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\economy_model.nls)
  called by procedure RUN-ECONOMIC-CYCLE (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\economy_model.nls)
  called by procedure GO
  called by procedure RUN-WORK-FROM-HOME (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace.nls)
  called by procedure EXECUTE-AND-SAVE (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace.nls)
  called by procedure BEHAVIOURSPACE-LOAD-VARIABLE (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace_utils.nls)
  called by procedure BEHAVIOURSPACE-SATISFACTION-SCENARIO-1-2 (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace_scenario_1_checks.nls)
  called by procedure BEHAVIOURSPACE-SATISFACTION-SCENARIO-1 (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace_scenario_1_checks.nls)
  called by procedure BEHAVIOURSPACE-GLOBAL-FITNESS-VALUE (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace.nls)
  called by Command Center

ERROR 2
Requested 294 random agents from a set of only 206 agents.
error while observer running N-OF
  called by procedure PERFORM-DAILY-TESTING-PUBLIC-MEASURE (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\public_measures\testing.nls)
  called by procedure APPLY-ACTIVE-MEASURES (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\public_measures\public_measures.nls)
  called by procedure GO
  called by procedure EXECUTE-AND-SAVE (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace.nls)
  called by procedure BEHAVIOURSPACE-LOAD-VARIABLE (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace_utils.nls)
  called by procedure BEHAVIOURSPACE-SCENARIO-3-PEAK-FULL-TESTING (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace_scenario_3_checks.nls)
  called by procedure BEHAVIOURSPACE-SCENARIO-3-COMPARISON-10-100-LOWER-PEAK (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace_scenario_3_checks.nls)
  called by procedure BEHAVIOURSPACE-SCENARIO-3-GLOBAL-CHECK (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace_scenario_3_checks.nls)
  called by procedure BEHAVIOURSPACE-GLOBAL-FITNESS-VALUE (C:\Users\Maarten\Google Drive\Corona-Research\Program\Netlogo versions\COVID-sim-master (19) 0e05f24\simulation_model\behaviourspace.nls)
  called by Command Center

**Comment by rmellema** [comment] 2020-05-25 09:19
This second error has been fixed. I think the first one as well (I can see a code path in the function that throws an error for gathering points), so I'll close this for now. 
Feel free to reopen this if the issue is not actually solved.

**Closed as completed by rmellema** 2020-05-25 09:19 UTC
